version: 2

build:
  os: "ubuntu-20.04"
  tools:
    python: "miniconda3-4.7"

# Build all formats
formats: all

# Build from the docs/ directory with Sphinx
sphinx:
  configuration: Docs/conf.py

# Explicitly set the dependencies
conda:
  environment: environment_linux.yml